name: Development Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-20.04'
            target: 'x86_64-unknown-linux-gnu'
            name: 'linux-x64'
          - platform: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            name: 'windows-x64'

    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npm run build

      - name: Build Tauri app (dev)
        run: npm run tauri build -- --debug

      - name: Upload development artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: dev-build-${{ matrix.name }}-${{ github.sha }}
          path: |
            src-tauri/target/debug/bloodyboss-config*
            src-tauri/target/debug/*.exe
          retention-days: 7